### ISSUE TITLE
Pascal 5i dataloader bgr

### ISSUE THREAD

**Issue by ahyunSeo** [MSiam/AdaptiveMaskedProxies#11]
Hello,
Thank you for your nice work.
I was looking around you dataloaders.
In specific, I was wondering about pascal-5i.
I could not find any part that convert bgr (due to the cv2.imread) to rgb in the following file.

https://github.com/MSiam/AdaptiveMaskedProxies/blob/master/ptsemseg/loader/pascal_voc_5i_loader.py#L129

Or should I refer to the pascal-multirun branch? It seems like it uses ss datalayer scheme and uses rgb instead.

Thank you,
Ahyun

**Comment by MSiam** [comment]
Hello Sorry for late reply and thanks for pointing that out. I fixed it now it should improve the results. I was initially using the OSLSM loader which I was directling reading PIL Image so didnt have that issue in this branch. Check [here](https://github.com/MSiam/AdaptiveMaskedProxies/blob/prev_results/ptsemseg/loader/oslsm/util.py) last line for what I am talking about, but I switched to the other loader which I just used the image pair dumped from OSLSM loader directly. Since all the literature was evaluating on 1000 samples directly. However PANet which was also published in ICCV have proposed using an average of multiple runs with different seeds when sampling the 1000 pairs and I think that is the best to do and is what I am doing in my new work too.
